name: First workflow

on:
  push

jobs:
  build_n_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install valgrind and cppcheck
        run: sudo apt-get install -y valgrind cppcheck
      - name: Build the app
        run: ./buildcheck.sh
      - name: Generate outputs from units
        run: ./test/generate_outputs.sh
      - name: Run JsonParser unit tests
        run: ./test/JsonParser_test
      - name: run Makefile
        run: make all
      - uses: actions/upload-artifact@v2
        with:
          path: ./performance_and_style_report.txt
