name: First workflow

on:
  push

jobs:
  build_n_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install valgrind and cppcheck
        run: sudo apt-get install -y valgrind cppcheck
      - name: build
        run: g++-9 -Wall -Wextra -Werror -std=c++17 -lstdc++fs *.cpp 
      - name: run Makefile
        run: make alltest
      - uses: actions/upload-artifact@v2
        with:
          path: ./performance_and_style_report.txt
