name: First workflow

on:
  push

jobs:
  build_n_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the app
        run: g++ -Wall -std=c++17 *.cpp -o a.out
      - name: Generate outputs from units
        run: ./test/generate_outputs.sh
      - name: Check if generated outputs are good
        run: diff test/outputs.txt test/good_outputs.txt