name: First workflow

on:
  push

jobs:
  build_n_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the app
        run: g++ -std=c++17 *.cpp -o a.out
      - name: Check memora leaks
        run: apt-get install -y valgrind 
        run: valgrind --leak-check=full --error-exitcode=1 ./a.out test/units/unit1.json test/units/unit2.json
      - name: Generate outputs from units
        run: ./test/generate_outputs.sh
      - name: Check if generated outputs are good
        run: diff test/outputs.txt test/good_outputs.txt